name: pyTruthTable
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python>=3.8
  - anaconda
  - pip
  - libpython-static
  - customtkinter
  - tk
  - pip:
    - truth-table-generator
    - CTkTable
    - nuitka